# Generated by Django 5.1 on 2024-08-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userbehavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('url_id', models.CharField(max_length=200)),
            ],
        ),
    ]
